# Generated by Django 4.2.17 on 2025-01-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
